name: streamdiffusion2
channels:
  - bioconda
  - anaconda
  - nvidia
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - expat=2.7.1
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - ncurses=6.4
  - openssl=3.0.16
  - pip=25.1
  - pthread-stubs=0.3
  - python=3.10.18
  - readline=8.2
  - setuptools=78.1.1
  - sqlite=3.45.3
  - tk=8.6.14
  - tzdata=2025b
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - accelerate==1.8.1
      - antlr4-python3-runtime==4.9.3
      - certifi==2022.12.7
      - charset-normalizer==2.1.1
      - colored==2.3.0
      - coloredlogs==15.0.1
      - cuda-bindings==12.9.0
      - cuda-python==12.9.0
      - diffusers==0.24.0
      - filelock==3.13.1
      - fire==0.7.0
      - flatbuffers==25.2.10
      - fsspec==2024.6.1
      - hf-xet==1.1.5
      - huggingface-hub==0.25.2
      - humanfriendly==10.0
      - idna==3.4
      - importlib-metadata==8.7.0
      - jinja2==3.1.4
      - markupsafe==2.1.5
      - mpmath==1.3.0
      - networkx==3.3
      - numpy==1.26.4
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cublas-cu12==12.9.1.4
      - nvidia-cuda-nvrtc-cu12==12.9.86
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cudnn-cu11==9.10.2.21
      - nvidia-cudnn-cu12==8.9.4.25
      - omegaconf==2.3.0
      - onnx==1.15.0
      - onnx-graphsurgeon==0.3.26
      - onnxruntime==1.16.3
      - opencv-python==4.11.0.86
      - packaging==25.0
      - pillow==11.0.0
      - polygraphy==0.47.1
      - protobuf==3.20.2
      - psutil==7.0.0
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests==2.28.1
      - safetensors==0.5.3
      - streamdiffusion==0.1.1
      - sympy==1.13.3
      - tensorrt==9.0.1.post11.dev4
      - tensorrt-bindings==9.0.1.post11.dev4
      - tensorrt-libs==9.0.1.post11.dev4
      - termcolor==3.1.0
      - tokenizers==0.19.1
      - torch==2.1.0+cu121
      - torchvision==0.16.0+cu121
      - tqdm==4.67.1
      - transformers==4.44.0
      - triton==2.1.0
      - typing-extensions==4.12.2
      - urllib3==1.26.13
      - xformers==0.0.22.post7
      - zipp==3.23.0
prefix: /research/cbim/vast/sf895/miniforge3/envs/streamdiffusion2
